#!/usr/bin/env python3
"""
Event Types Generator Core

Scans Roblox project for Events.lua files and generates type definitions
"""

import os
import re
from pathlib import Path
from typing import Dict, List, Tuple


def parse_events_file(events_file_path: Path) -> Dict[str, str]:
    """
    Parse an Events.lua file to extract event names and their types.
    Returns a dict like: {"Skip": "RemoteEvent", "GiveItem": "BindableEvent"}
    """
    try:
        with open(events_file_path, 'r', encoding='utf-8') as f:
            content = f.read()

        events = {}

        # Match patterns like: EventName = EventTypes.RemoteEvent,
        pattern = r'(\w+)\s*=\s*EventTypes\.(\w+)'
        matches = re.findall(pattern, content)

        for event_name, event_type in matches:
            events[event_name] = event_type

        return events
    except Exception as e:
        print(f'Error parsing {events_file_path}: {e}')
        return {}


def find_all_services(server_script_service_path: Path) -> Dict[str, Dict[str, str]]:
    """Scan ServerScriptService for folders with Events.lua files"""
    services = {}

    try:
        for item in os.listdir(server_script_service_path):
            item_path = server_script_service_path / item
            if item_path.is_dir():
                events_file = item_path / 'Events.lua'
                if events_file.exists():
                    events = parse_events_file(events_file)
                    services[item] = events
    except Exception as e:
        print(f'Error scanning directory: {e}')

    return dict(sorted(services.items()))


def generate_types_file(services: Dict[str, Dict[str, str]]) -> str:
    """Generate the EventManagerTypes.lua content"""
    lines = [
        '--!strict',
        '--[[',
        '\tEventManager Type Definitions',
        '',
        '\tAuto-generated by roblox-event-generator',
        '\tDo not edit manually - run the generator script instead!',
        '',
        '\tWhen you add a new service with Events.lua:',
        '\t1. Create YourService/Events.lua with event definitions using EventTypes',
        '\t2. Add to ServerMain EventManager.initialize()',
        '\t3. Run: roblox-event-generator',
        ']]',
        '',
        'export type EventManagerType = {',
        '\t-- API Functions',
        '\tcreateServiceEvents: (serviceName: string, eventDefinitions: any) -> any,',
        '\tinitialize: (serviceFolders: { Folder }) -> (),',
        '\tinitializeService: (serviceFolder: Folder) -> any?,',
        '\tgetEvents: (serviceName: string) -> any?,',
        '\tgetServiceEvents: (serviceName: string) -> any?,',
        '\twaitForEvent: (serviceName: string, eventName: string, eventType: string?) -> any?,',
        '\tfireAllEvents: (player: Player, events: any, value: any?) -> (),',
        '\tfireUnknownEvent: (player: any, event: any, params: any) -> (),',
        '',
        '\t-- Service Properties (auto-generated with event types)',
    ]

    # Add each service with its specific event types
    for service_name, events in services.items():
        if not events:
            # No events parsed, use generic type
            lines.append(f'\t{service_name}: {{ [string]: any }},')
            continue

        lines.append(f'\t{service_name}: {{')
        for event_name, event_type in sorted(events.items()):
            lines.append(f'\t\t{event_name}: {event_type},')
        lines.append('\t},')

    lines.extend(['}', '', 'return nil', ''])

    return '\n'.join(lines)


def generate(
    project_root: Path,
    src_dir: str = 'src',
    output_path: str = 'src/ReplicatedStorage/_Libs/EventManagerTypes.lua'
) -> Tuple[int, int]:
    """
    Generate EventManagerTypes.lua for a Roblox project

    Args:
        project_root: Root directory of the Roblox project
        src_dir: Source directory relative to project root (default: 'src')
        output_path: Output file path relative to project root

    Returns:
        Tuple of (num_services, num_events)
    """
    server_script_service = project_root / src_dir / 'ServerScriptService'
    output_file = project_root / output_path

    if not server_script_service.exists():
        raise FileNotFoundError(
            f"ServerScriptService not found at {server_script_service}\n"
            f"Make sure you're running this from your Roblox project root."
        )

    services = find_all_services(server_script_service)

    total_events = sum(len(events) for events in services.values())

    content = generate_types_file(services)

    # Ensure output directory exists
    output_file.parent.mkdir(parents=True, exist_ok=True)

    output_file.write_text(content, encoding='utf-8')

    return len(services), total_events
